INSERT INTO FFNB_Master.clubs (code_club, nom, id_secretariat, nr_ligue_responsable, nbre_nageurs)
VALUES  ('AZSC', 'Koninklijke Antwerpsezwemclub Scaldis', 1, NULL, NULL),
        ('AZV', 'Arendonkse zwemclub', 1, NULL, NULL),
        ('BZTC', NULL, 1, NULL, NULL),
        ('CCM', 'Castor club de Mons', 3, NULL, NULL),
        ('CCS', 'Club communal natation Marche en Famenne', 1, NULL, NULL),
        ('CHAN', 'Charleroi association natation', 2, NULL, NULL),
        ('CHTHN', NULL, 4, NULL, NULL),
        ('CNA', 'Cercle de natation Arlonais', 1, NULL, NULL),
        ('CNBA', 'Cercle Royal de natation de Bruxelles Atalante', 1, NULL, NULL),
        ('CNHUY', 'Cercle Royal de natation de Huy', 1, NULL, NULL),
        ('CNJ', 'Cercle de natation Jodoignois', 3, NULL, NULL),
        ('CNMA', NULL, 2, NULL, NULL),
        ('CNSW', NULL, 4, NULL, NULL),
        ('COUNT', 'Country swimming club la Calaine Neu-Moresnet', 1, NULL, NULL),
        ('DCTP', 'Dauphin club Trois Ponts', 4, NULL, NULL),
        ('DMB', 'Zwemvereniging de Meerkoet Bree', 4, NULL, NULL),
        ('EMBOU', 'Embourg natation', 1, NULL, NULL),
        ('ENN', 'Ecole de natation de Nivelles', 3, NULL, NULL),
        ('ESN', 'Ecole Seraing Natation', 1, NULL, NULL),
        ('GBZ', 'Groot Beverse Zwemclub', 3, NULL, NULL),
        ('HZA', 'Heistse zwemclub Arduas', 3, NULL, NULL),
        ('HZC', NULL, 2, NULL, NULL),
        ('HZS', 'Koninklijke Hasselte zwemvereniging Spartacus', 2, NULL, NULL),
        ('IKZ', NULL, 3, NULL, NULL),
        ('KZK', 'Koninklijke Kortrijkse zwemkring', 4, NULL, NULL),
        ('LDV', 'Les dauphins Visetois', 2, NULL, NULL),
        ('LZV', 'Loverse zwemvereniging', 3, NULL, NULL),
        ('MOZKA', 'Molse zwemclub Mozka', 2, NULL, NULL),
        ('MZVA', NULL, 1, NULL, NULL),
        ('NCG', NULL, 4, NULL, NULL),
        ('NEREU', 'Cercle de natation Nereu Ganshoren', 1, NULL, NULL),
        ('NOC', 'Namur Olympic club', 1, NULL, NULL),
        ('NSG', 'Societe Royale La nage Saint-Gilles', 4, NULL, NULL),
        ('OCEAN', NULL, 2, NULL, NULL),
        ('OLD D', NULL, 3, NULL, NULL),
        ('OLMA', NULL, 1, NULL, NULL),
        ('OSC', NULL, 4, NULL, NULL),
        ('OZEKA', NULL, 4, NULL, NULL),
        ('RBP', 'Koninkijke Antwerpsezwemclub scaldis', 1, NULL, NULL),
        ('RSCM', NULL, 3, NULL, NULL),
        ('SCC', 'Swimming club Calypso Watermael Boitsfort', 4, NULL, NULL),
        ('SL', 'Swimming Luxembourg', 1, NULL, NULL),
        ('SNC', NULL, 1, NULL, NULL),
        ('SOZ', 'Sorghvliet zwemclub', 1, NULL, NULL),
        ('SVAZ', 'Sportvereniging Aarselaar zwemmen', 1, NULL, NULL),
        ('TENBO', NULL, 3, NULL, NULL),
        ('TZV', 'Koninklijke Turnhoutse Zwemvereniging', 4, NULL, NULL),
        ('USG', NULL, 1, NULL, NULL),
        ('VN', 'Royal Verviers natation', 1, NULL, NULL),
        ('VU/DG', NULL, 1, NULL, NULL),
        ('W', NULL, 2, NULL, NULL),
        ('WSD', NULL, 1, NULL, NULL),
        ('WZV', 'Wemmelse zwemvereniging', 3, NULL, NULL),
        ('YSC', NULL, 4, NULL, NULL),
        ('ZCK', 'Zwemclub Kapelle-O/D-Bos', 4, NULL, NULL),
        ('ZCM', 'Zwemclub Maasmechelen', 2, NULL, NULL),
        ('ZD', 'Zolderse Dolfijnen', 2, NULL, NULL),
        ('ZDKK', NULL, 1, NULL, NULL),
        ('ZIK', 'Zwemclub iloka Kapellen', 2, NULL, NULL),
        ('ZN', 'Nijlense Zwemclub', 2, NULL, NULL),
        ('ZNA', 'Koninklijke zwemclub Neptunus Aalst', 3, NULL, NULL),
        ('ZOLA', 'Zwemclub Olympic Antwerpen', 2, NULL, NULL),
        ('ZVH', NULL, 3, NULL, NULL),
        ('ZVL', NULL, 3, NULL, NULL),
        ('ZZV', NULL, 3, NULL, NULL);